version: '3.4'

services:
  MonogoDatabase:
    image: mongo

  microshop.catalogs.endpointapi:
    image: ${DOCKER_REGISTRY-}microshopcatalogsendpointapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: src/Services/Catalogs/03. Endpoint/MicroShop.Catalogs.EndpointApi/Dockerfile